services:
  sentinel:
    image: mmatvoz/openplanetracker-sentinel:latest
    container_name: sentinel
    privileged: true
    ports:
      - "8001:8001"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev/bus/usb:/dev/bus/usb
      - opt_config_data:/config

volumes:
  opt_config_data:
    name: opt_config_data
